package com.pointlion.sys.mvc.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({ "serial", "unchecked" })
public abstract class BaseAnswer<M extends BaseAnswer<M>> extends Model<M> implements IBean {

	public M setId(java.lang.String id) {
		set("id", id);
		return (M) this;
	}

	public java.lang.String getId() {
		return getStr("id");
	}

	public M setDescrible(java.lang.String describle) {
		set("describle", describle);
		return (M) this;
	}

	public java.lang.String getDescrible() {
		return getStr("describle");
	}

	public M setCreateTime(java.lang.String createtime) {
		set("createtime", createtime);
		return (M) this;
	}

	public java.lang.String getCreateTime() {
		return getStr("createtime");
	}

	public M setTopicId(java.lang.String topicid) {
		set("topicid", topicid);
		return (M) this;
	}

	public java.lang.String getTopicId() {
		return getStr("topicid");
	}

	public M setQuestionId(java.lang.String questionid) {
		set("questionid", questionid);
		return (M) this;
	}

	public java.lang.String getQuestionId() {
		return getStr("questionid");
	}

	public M setEvaluate(java.lang.String evaluate) {
		set("evaluate", evaluate);
		return (M) this;
	}
	
	public java.lang.String getEvaluate() {
		return getStr("evaluate");
	}
	
	public M setScore(java.lang.String score) {
		set("score", score);
		return (M) this;
	}

	public java.lang.String getScore() {
		return getStr("score");
	}

	public M setPersonId(java.lang.String personid) {
		set("personid", personid);
		return (M) this;
	}

	public java.lang.String getPersonId() {
		return getStr("personid");
	}
	
	public M setRId(java.lang.String rid) {
		set("rid", rid);
		return (M) this;
	}

	public java.lang.String getRId() {
		return getStr("rid");
	}
	
	public M setFId(java.lang.String fid) {
		set("fid", fid);
		return (M) this;
	}
	
	public java.lang.String getFId() {
		return getStr("fid");
	}
}
