package com.pointlion.sys.mvc.common.model;

import java.util.List;

import com.jfinal.aop.Before;
import com.jfinal.plugin.activerecord.Page;
import com.jfinal.plugin.activerecord.tx.Tx;
import com.pointlion.sys.mvc.common.model.base.BaseAnswer;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Answer extends BaseAnswer<Answer> {

	public final static Answer dao = new Answer();

	/**
	 * 获得分页数据
	 */
	public Page<Answer> getAnswerPage(Integer curr, Integer pagesize) {
		return Answer.dao.paginate(curr, pagesize, "select * ", " from t_answer");
	}
	
	/**
	 * 获得分页数据
	 */
	public List<Answer> getAnswerList(String topicid, String userid) {
		return Answer.dao.find("select * from t_answer where topicid = '" + topicid + "' and personid ='" + userid + "'");
	}
	
	/**
	 * 获得分页数据
	 */
	public Page<Answer> getAnswerPage(Integer curr, Integer pagesize, String topicid) {
		return Answer.dao.paginate(curr, pagesize, "select * ", " from t_answer where topicid = '" + topicid + "'");
	}
	
	/**
	 * 获得分页数据
	 */
	public Page<Answer> getAnswerPage(Integer curr, Integer pagesize, String questionid, String userid) {
		return Answer.dao.paginate(curr, pagesize, "select * ",
				" from t_answer where questionid = '" + questionid + "' and personid ='" + userid + "'");
	}
	
	/**
	 * 获得分页数据
	 */
	public Page<Answer> getAnswerPageByUser(Integer curr, Integer pagesize, String topicid, String userid) {
		return Answer.dao.paginate(curr, pagesize, "select * ", " from t_answer where topicid = '" + topicid + "' and personid ='" + userid + "'");
	}
	
	/**
	 * 根据fid查询Answer
	 * @param fid
	 * @return
	 */
	public Answer getAnswerByFid(String fid){
		List<Answer> list = Answer.dao.find("select * from t_answer where fid ='"+fid+"'");
		if(list!=null && list.size()>0){
			return list.get(0);
		}else{
			return null;
		}
	}

	/***
	 * 删除
	 * 
	 * @param ids
	 */
	@Before(Tx.class)
	public void deleteByIds(String ids) {
		String idarr[] = ids.split(",");
		for (String id : idarr) {
			Answer answer = Answer.dao.findById(id);
			answer.delete();
		}
	}
}