package com.pointlion.sys.mvc.common.model;

import java.util.List;

import com.jfinal.aop.Before;
import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.tx.Tx;
import com.pointlion.sys.mvc.common.model.base.BaseFileConfig;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FileConfig extends BaseFileConfig<FileConfig> {
	public static final FileConfig dao = new FileConfig();
	
	@Before(Tx.class)
	public List<FileConfig> selectByQuestionid(String questionid) {
		return FileConfig.dao.find("select * from t_file_config where questionid = '"+questionid+"'");
	}
	
	@Before(Tx.class)
	public void deleteByQuestionid(String questionid) {
		FileConfig.dao.find("delete from t_file_config where questionid = '"+questionid+"'");
	}
}
